### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by NNowakowski** [KageDev/VRCDynamicBones#1]
Do I need to add a "Dynamic Bones Collider" to my avatars hands or will it work without?
It seems to work without at times, but other times it just doesn't work at all, even tho I can see they have bones on their ears for example.

**Comment by KageDev** [comment]
Yes, you need to add DynamicBoneCollider component to your avatar's hands. Most public avatars in VRChat have this, but some don't.

**Comment by NNowakowski** [comment]
Thanks, that would explain why my custom avatars weren't able to interact with others!
